[tool.black]
line-length = 79
target-version = ['py311']
extend-exclude = '''
(
  migrations
)
'''
[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
skip_gitignore = true
skip_glob = ["**/migrations/*", "**/settings/*"]
src_paths = ["/home/alexander/test_tasks/test-task-hightech-plant/user_profiles"]
